### ISSUE TITLE
How to get the subject and the content of the mail

### ISSUE THREAD

**Issue by lefred** [lefred/mailspring-libre-gtg#2]
I'm still trying to find how to get the info of the mail focused/active in the MessageList

**Comment by notpushkin** [comment]
Depending on where you're trying to use it, the message object could be passed as `this.props.message`, or you can also try to retrieve it from [FocusedContentStore](https://foundry376.github.io/Mailspring/classes/FocusedContentStore.html) somehow. Then you can get `message.subject` and `message.body`, and other fields are [available too](https://foundry376.github.io/Mailspring/classes/Message.html).

**Comment by lefred** [comment]
Thank you, 

I've found the subject (using FocusedContentStore) however, I can find the threadid but I'm not able to get the body of the message. The code looks like this:
```
const thread = FocusedContentStore.focused('thread');
var topic = thread.subject
```

**Comment by lefred** [comment]
Hi @notpushkin I finally made it, thank you for the help.

However, do you know how I could import convertToPlainText and convertFromHTML from conversion inside a plugin ? (see https://github.com/lefred/mailspring-libre-gtg/commit/43bad12ada4b58e385a018798e4e5e2332f4ec17)

Cheers,
